---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: pihole
  labels:
    app: pihole
    component: pihole
    tier: frontend
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
    component: pihole
    tier: frontend
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: dns-udp
  - name: client-udp
    protocol: UDP
    port: 67
    targetPort: client-udp
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.0.201 
  sessionAffinity: None