---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-dnsmasq
  namespace: pihole
  labels:
    app: pihole
    component: pihole
data:
  02-custom.conf: |
    address=/foo.bar/192.168.178.10