---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: pihole
  labels:
    app: pihole
    component: pihole
    tier: storage
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: pihole-storage
  hostPath:
    path: "/mnt/pihole"