---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
    component: pihole
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
      component: pihole
      tier: frontend
  template:
    metadata:
      labels:
        app: pihole
        component: pihole
        tier: frontend
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:v5.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: pihole-https
          protocol: TCP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        envFrom:
        - configMapRef:
            name: pihole-config
        - secretRef:
            name: pihole-secrets
        volumeMounts:
        - name: pihole-vm
          mountPath: /etc/pihole
        - name: pihole-vm-custom-dnsmasq
          mountPath: /etc/dnsmasq.d/02-custom.conf
          subPath: 02-custom.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: pihole-vm
        persistentVolumeClaim:
          claimName: pihole-pvc
      - name: pihole-vm-custom-dnsmasq
        configMap:
          name: pihole-custom-dnsmasq
          defaultMode: 420
status: {}