---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
  labels:
    app: pihole
    component: pihole
    tier: frontend
data:
  ServerIP: 192.168.0.201  
  TZ: 'Europe/Warsaw'
  DNS1: 8.8.4.4
  DNS2: 8.8.8.8
