---
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: pihole
  labels:
    app: pihole
    component: pihole
    tier: frontend
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
    component: pihole
    tier: frontend
  ports:
  - name: pihole-http
    protocol: TCP
    port: 80
    targetPort: pihole-http
  - name: pihole-https
    protocol: TCP
    port: 443
    targetPort: pihole-https
  - name: dns
    protocol: TCP
    port: 53
    targetPort: dns
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.0.201
  type: LoadBalancer
  sessionAffinity: None