---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secrets
  namespace: pihole
  labels:
    app: pihole
    component: pihole
    tier: frontend
type: Opaque
data:
  # echo -n 'pihole' | base64
  WEBPASSWORD: cGlob2xl