---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-pihole.fullname" . }}-custom-dnsmasq
  labels:
    {{- include "kubernetes-pihole.labels" . | nindent 4 }}
data:
  02-custom.conf: |
    address=/foo.bar/192.168.178.10