apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-pihole.fullname" . }}
  labels:
    {{- include "kubernetes-pihole.labels" . | nindent 4 }}
type: Opaque
data:
  WEBPASSWORD: {{.Values.webpassword}}