apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-pihole.fullname" . }}-tcp
  labels:
    {{- include "kubernetes-pihole.labels" . | nindent 4 }}
  {{- with .Values.loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.services.serverIP }}
  ports:
    - port: {{ .Values.services.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.services.https.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "kubernetes-pihole.selectorLabels" . | nindent 4 }}
