{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-pihole.serviceAccountName" . }}
  labels:
{{ include "kubernetes-pihole.labels" . | nindent 4 }}
{{- end -}}
